"""add contact password

Revision ID: 3ca0d46fcd6f
Revises: 407bbdc209f1
Create Date: 2023-12-24 00:32:49.409401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca0d46fcd6f'
down_revision: Union[str, None] = '407bbdc209f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'password')
    # ### end Alembic commands ###
