"""add contact refresh_token

Revision ID: d560f737db5f
Revises: 3ca0d46fcd6f
Create Date: 2023-12-24 09:28:01.913292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd560f737db5f'
down_revision: Union[str, None] = '3ca0d46fcd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('refresh_token', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'refresh_token')
    # ### end Alembic commands ###
